logging.level:
#  org.springframework.context: WARN
#  org.springframework.data: WARN
#  org.springframework.jdbc: WARN
#  example: DEBUG
  ROOT: INFO

spring:

  web:
    locale: en_US

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

  kafka:
    streams:
      state-store-cache-max-size: 100